server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8718

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true # 开启sentinel对feign的支持