server:
  port: 8001

spring:
  application:
    name: cloud-provider-service
  datasource:
    url: jdbc:mysql://localhost:3306/my_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.humid.springcloud.entities  # entity 别名类所在包