server:
  port: 8002
spring:
  application:
    name: cloud-consumer-service

eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka
      defaultZone: http://127.0.0.1:7001/eureka,http://192.168.1.132:7002/eureka # 集群版
    # 表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
  instance:
    instance-id: consumer8002
