server:
  port: 8010

spring:
  application:
    name: cloud-provider-service
  datasource:
    url: jdbc:mysql://localhost:3306/my_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # entity 别名类所在包
  type-aliases-package: com.humid.springcloud.entities

eureka:
  client:
    service-url:
      # defaultZone: http://127.0.0.1:7001/eureka
      # 集群版
      defaultZone: http://127.0.0.1:7001/eureka,http://192.168.1.132:7002/eureka
    # 表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
  instance:
    instance-id: provider8010
    prefer-ip-address: true  # 访问路径可以显示IP地址